"""add meal entries

Revision ID: 0ead340494e7
Revises: d10ac8baf624
Create Date: 2026-02-19 21:17:44.221250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ead340494e7'
down_revision = 'd10ac8baf624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_meal_type'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_entry_date'))

    op.drop_table('meal_entries')
    # ### end Alembic commands ###
