"""add macro goals and weight entries

Revision ID: 479c7e03c9ce
Revises: 0ead340494e7
Create Date: 2026-02-19 22:43:20.688804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479c7e03c9ce'
down_revision = '0ead340494e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calories_target', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=False),
    sa.Column('carbs_target_g', sa.Float(), nullable=False),
    sa.Column('fat_target_g', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_goals_user_id'), ['user_id'], unique=True)

    op.create_table('weight_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_weight_user_date')
    )
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_weight_entries_entry_date'))

    op.drop_table('weight_entries')
    with op.batch_alter_table('macro_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_goals_user_id'))

    op.drop_table('macro_goals')
    # ### end Alembic commands ###
