"""add workout exercises and sets

Revision ID: d10ac8baf624
Revises: 347f698ae26a
Create Date: 2026-02-19 18:28:36.171066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10ac8baf624'
down_revision = '347f698ae26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercises_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_exercises_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_exercise_id'), ['exercise_id'], unique=False)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workouts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_workout_date'), ['workout_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_workout_date'))
        batch_op.drop_index(batch_op.f('ix_workouts_user_id'))
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_exercise_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_exercises_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_exercises_name'))

    op.drop_table('workout_exercises')
    # ### end Alembic commands ###
