"""Timezone-aware timestamps

Revision ID: f623737438ce
Revises: 479c7e03c9ce
Create Date: 2026-03-01 01:31:50.783673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f623737438ce'
down_revision = '479c7e03c9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('macro_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calories_target', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=False),
    sa.Column('carbs_target_g', sa.Float(), nullable=False),
    sa.Column('fat_target_g', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_goals_user_id'), ['user_id'], unique=True)

    op.create_table('meal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_user_id'), ['user_id'], unique=False)

    op.create_table('weight_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_weight_user_date')
    )
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_entries_user_id'), ['user_id'], unique=False)

    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_workout_date'), ['workout_date'], unique=False)

    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercises_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_exercises_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_exercise_id'), ['exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_exercise_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_exercises_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_exercises_name'))

    op.drop_table('workout_exercises')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_workout_date'))
        batch_op.drop_index(batch_op.f('ix_workouts_user_id'))

    op.drop_table('workouts')
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_weight_entries_entry_date'))

    op.drop_table('weight_entries')
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_meal_type'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_entry_date'))

    op.drop_table('meal_entries')
    with op.batch_alter_table('macro_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_goals_user_id'))

    op.drop_table('macro_goals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
